### ISSUE TITLE
Why have an empty changelog when git log could be used ?

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/mate-netspeed#26]
Hi all, 
Why have an empty changelog when output of git log would be good enough.

**Comment by raveit65** [comment]
we will generate changelog with 1.14.

**Comment by monsta** [comment]
@shirishag75: it will be done when making the tarballs. Also please note that ```mate-netspeed``` had been merged into ```mate-applets``` for 1.14, so here you'll see no changes (and no 1.14 tarball, actually).
