### ISSUE TITLE
Is mate-netspeed ported over to gsettings ?

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/mate-netspeed#27]
Hi there, 
Just saw this bug https://bugs.debian.org/772619 according to which it will FTBFS (Fail To Build From Source) because it has deprecated functions. This might affect mate-netspeed as I am guessing you would also be using gsettings as well. 

Looking forward to know.

**Comment by monsta** [comment]
There are no gconf-related functions in the code.
