### ISSUE TITLE
Shorten unit legend doesn't reduce space used

### ISSUE THREAD

**Issue by jean** [mate-desktop/mate-netspeed#34]
In preferences, select "Shorten unit legend". Now the speed displays only `K` instead of `KiB/s`, however now blank space is displayed instead of the `iB/s`. 
Instead of blank space, move the up/down displays closer to each other.

**Comment by raveit65** [comment]
On a horizontal panel i see always 'b' or 'K' if units are shortened and there is no space to the appleft left.
Note this is with gtk3 version.

**Comment by jean** [comment]
Here's a screenshot with mouse pointer pointing at the gap that would otherwise contain `iB/s`. Instead of a gap, the `K` should move up closer to the up-arrow. 
![extra-space](https://cloud.githubusercontent.com/assets/84800/10911839/4b84f53e-8279-11e5-83b2-c3f1d6bfc5cd.png)

**Comment by raveit65** [comment]
hmm, i don't see that here on my box with 1.10/11 packages.
![netspeed](https://cloud.githubusercontent.com/assets/961604/10920756/2fab09ea-8272-11e5-9a64-4618ca2fbdab.png)
Maybe it's an issue with older versions, Which mate-netspeed version are you using and which distro?

**Comment by jean** [comment]
Indeed ...

$ apt-cache show mate-netspeed
Package: mate-netspeed
Version: 1.10.0-1+rafaela

Linux Mint 17.2 Rafaela

**Comment by raveit65** [comment]
confirmed with gtk2 version (1.10.x) . I see the issue also if 'Shorten unit legend' isn't used.

**Comment by monsta** [comment]
As of 1.14 release, this project has been merged into ```mate-applets```. GitHub does not allow us to move issues between projects, so if you still see the issue, please file a new report in
https://github.com/mate-desktop/mate-applets/issues/
