### ISSUE TITLE
Feature request: Switch to active interface

### ISSUE THREAD

**Issue by jean** [mate-desktop/mate-netspeed#35]
It would be cool if the widget could switch to the currently active interface. E.g. when switching from `wlan0` to `usb0`.

**Comment by monsta** [comment]
Which one should be considered active (let's assume they're all ```up``` and ```running``` in ```ifconfig```'s output)?

**Comment by jean** [comment]
> Which one should be considered active (let's assume they're all up and
running in ifconfig's output)?

Hmm the one that's being used ... i.e. I see if `usb0` is up, then `wlan0`
is ignored, even though both appear in `ifconfig`'s output.
I think this depends on the interface metric:

```
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use
Iface
0.0.0.0         192.168.42.129  0.0.0.0         UG    0      0        0 usb0
192.168.42.0    0.0.0.0         255.255.255.0   U     1      0        0 usb0
192.168.43.0    0.0.0.0         255.255.255.0   U     9      0        0
wlan0
```

It looks like it's the interface with a lower metric that is used.
I don't know how the metric gets set.

**Comment by monsta** [comment]
As of 1.14 release, this project has been merged into ```mate-applets```. GitHub does not allow us to move issues between projects, so if you still need the feature, please file a new report in
https://github.com/mate-desktop/mate-applets/issues/
