### ISSUE TITLE
can't avoid vmnet IF when pointed to "Default" 

### ISSUE THREAD

**Issue by Lvceo** [mate-desktop/mate-netspeed#36]
As I have a VMware Workstation installed on my computer, vmnet1&8 appears in the list of IF availables to netspeed, and when the Preferences/General Settings/Network device : point to "Default", then NetSpeed shows me the traffic speed of this IF (which I don't want), instead of my wlan0 or eth0, for i.e.

So the question is : if I want to disable theses IF from the list of Network device, I got no way to do it.
Even if I reconfigure NetworkManager to avoid theses IF from its conf.
/etc/NetworkManager/NetworkManager.conf:
...
[keyfile]
unmanaged-devices=mac:00:50:56:c0:00:01;mac:00:50:56:c0:00:08
...

Is there anyway to do it in the future?

**Comment by monsta** [comment]
As of 1.14 release, this project has been merged into ```mate-applets```. GitHub does not allow us to move issues between projects, so if you still see the issue, please file a new report in
https://github.com/mate-desktop/mate-applets/issues/
